### ISSUE TITLE
Build Presto Landscape

### ISSUE THREAD

**Issue by caniszczyk** [prestodb/foundation#22]
It would be great to have a Presto Landscape

We can make it very simple like the GraphQL Landscape:
https://landscape.graphql.org/

I'd essentially have these categories:
* Project (Presto)
* Extensions (Cassanda, MySQL etc)
* Presto Adopters
* Presto Foundation Members

**Comment by galemccommons** [comment]
Work on this issue is in progress

**Comment by caniszczyk** [comment]
https://l.prestodb.io/
