### ISSUE TITLE
Host first GB meeting

### ISSUE THREAD

**Issue by caniszczyk** [prestodb/foundation#3]

**Comment by caniszczyk** [comment]
@brianwarner can you work with @achopragh to officially schedule the first GB meeting

The first week of December was suggested so budget can be approved, roadmap approved etc

**Comment by brianwarner** [comment]
Yep, definitely.  @achopragh, I'll be in touch shortly on this.

**Comment by caniszczyk** [comment]
The first GB meeting is scheduled for this Thursday
